// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzj-qYv9Ofjnued6Mpq48gxLyQvUu7qLs',
    appId: '1:551867854171:web:910a620af073dd68637e7e',
    messagingSenderId: '551867854171',
    projectId: 'bankdb-b800d',
    authDomain: 'bankdb-b800d.firebaseapp.com',
    storageBucket: 'bankdb-b800d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh6a3Bn9dNRbzGRlVltWJlcqocDt44w-A',
    appId: '1:551867854171:android:50e7d709a3310379637e7e',
    messagingSenderId: '551867854171',
    projectId: 'bankdb-b800d',
    storageBucket: 'bankdb-b800d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByK6lmCdXhVFgi05r8-KU_CL2GTjmTeSo',
    appId: '1:551867854171:ios:ae5519be8e3c1594637e7e',
    messagingSenderId: '551867854171',
    projectId: 'bankdb-b800d',
    storageBucket: 'bankdb-b800d.appspot.com',
    iosClientId: '551867854171-h81ss47h41lqaokom1cl7jp3eq26d4r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByK6lmCdXhVFgi05r8-KU_CL2GTjmTeSo',
    appId: '1:551867854171:ios:ae5519be8e3c1594637e7e',
    messagingSenderId: '551867854171',
    projectId: 'bankdb-b800d',
    storageBucket: 'bankdb-b800d.appspot.com',
    iosClientId: '551867854171-h81ss47h41lqaokom1cl7jp3eq26d4r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
